---
platform: linux
image: docker:///concourse/static-golang

inputs:
  - name: autopilot
    path: gopath/src/github.com/contraband/autopilot

run:
  path: gopath/src/github.com/contraband/autopilot/scripts/test.sh
